// flow-typed signature: e7e0280ff5dc7ea14fcc787a5fceb6cd
// flow-typed version: <<STUB>>/react-widgets-globalize_v^4.0.4/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-widgets-globalize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-widgets-globalize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-widgets-globalize/dist/react-widgets-globalize' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-widgets-globalize/dist/react-widgets-globalize.js' {
  declare module.exports: $Exports<'react-widgets-globalize/dist/react-widgets-globalize'>;
}
declare module 'react-widgets-globalize/index' {
  declare module.exports: $Exports<'react-widgets-globalize'>;
}
declare module 'react-widgets-globalize/index.js' {
  declare module.exports: $Exports<'react-widgets-globalize'>;
}
