// flow-typed signature: f09d75550b454a6871edefdd2a17e635
// flow-typed version: <<STUB>>/watchman_v^0.1.8/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'watchman'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'watchman' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'watchman/test' {
  declare module.exports: any;
}

declare module 'watchman/watchman' {
  declare module.exports: any;
}

// Filename aliases
declare module 'watchman/test.js' {
  declare module.exports: $Exports<'watchman/test'>;
}
declare module 'watchman/watchman.js' {
  declare module.exports: $Exports<'watchman/watchman'>;
}
